trigger: none
pr: none

resources:
  pipelines:
  - pipeline: 'ci-TaskFunctionApi-master'
    source: 'ci-TaskFunctionApi-master'
    trigger: true

jobs:
- job: Deploy
  displayName: 'Deploy to Azure App Service'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifacts'
    inputs:
      buildType: specific
      project: 'Cse415Finalproject' # Replace with the name of your Azure DevOps project
      pipeline: ci-TaskFunctionApi-master
      artifactName: 'drop'
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy to Azure App Service'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Cse415FinalProjectConnection'  # Replace with the name of your Azure service connection
      appType: 'webApp'
      WebAppName: 'cse415FinalProjectWebApp'  # Replace with the name of your Azure Web App
      packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/**/*.zip'
